/**
 * Custom Font Configuration
 *
 * This file contains type definitions for the custom icon font used in the Cypher mobile app.
 * The font is generated using IcoMoon.io and contains all custom icons.
 */

/**
 * Font family name for the custom icon font
 *
 * This constant should be used when referencing the custom font in styles
 * to ensure consistency across the application.
 */
export const CUSTOM_FONT_FAMILY = 'CydFont' as const;

/**
 * Type definition for all available icon names in the custom font
 *
 * This type ensures type safety when using icon names throughout the application.
 * When adding new icons, update this type to include the new icon names.
 */
export type IconNames =
  | 'account'
  | 'account-plus'
  | 'account-share'
  | 'activities'
  | 'addphoto'
  | 'airplane'
  | 'apple'
  | 'arrow-down-left'
  | 'arrow-left'
  | 'arrow-up-right'
  | 'atm-cash'
  | 'bar-graph'
  | 'bar-graph-filled'
  | 'bookmark'
  | 'bridge'
  | 'card'
  | 'card-filled'
  | 'card-load'
  | 'card-load-filled'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'close'
  | 'connect'
  | 'connected'
  | 'contactbook'
  | 'copy'
  | 'credit'
  | 'debit'
  | 'debit-card'
  | 'delete'
  | 'disconnect'
  | 'edit'
  | 'eye'
  | 'eye-closed'
  | 'Frame-10'
  | 'Frame-14'
  | 'freeze'
  | 'gas'
  | 'google'
  | 'headphone'
  | 'heart'
  | 'home'
  | 'home-filled'
  | 'ibc'
  | 'information'
  | 'key'
  | 'left-hand-pamp'
  | 'left-hand-pamp-filled'
  | 'link'
  | 'lock'
  | 'lock-1'
  | 'meter'
  | 'note'
  | 'notification'
  | 'options-vertical'
  | 'pos-machine'
  | 'qr-code'
  | 'qr-scanner'
  | 'refresh'
  | 'search'
  | 'settings'
  | 'share'
  | 'share-filled'
  | 'shield'
  | 'shield-tick'
  | 'shop'
  | 'star'
  | 'success'
  | 'swap-horizontal'
  | 'swap-vertical'
  | 'swipe'
  | 'telegram'
  | 'tick'
  | 'tools-wrench-screwdriver'
  | 'trend-up'
  | 'trend-up-bold'
  | 'triangle-down'
  | 'verified'
  | 'visa'
  | 'wallet'
  | 'wallet-connect'
  | 'wallet-multiple'
  | 'web'
  | 'web-filled'
  | 'wireless-left'
  | 'wireless-right'
  | 'withdraw'
  | 'card-plus'
  | 'paypal-icon'
  | 'apple-google-icon'
  | 'balance-scale'
  | 'help-circle-outline'
  | 'airdrop-icon'
  | 'sad-face'
  | 'happy-face'
  | 'edit-2'
  | 'nft-icon'
  | 'zap'
  | 'coins-stacked'
  | 'merchant'
  | 'arrow-forward';
