/**
 * Custom Font Configuration
 *
 * This file contains type definitions for the custom icon font used in the Cypher mobile app.
 * The font is generated using IcoMoon.io and contains all custom icons.
 */

/**
 * Font family name for the custom icon font
 *
 * This constant should be used when referencing the custom font in styles
 * to ensure consistency across the application.
 */
export const CUSTOM_FONT_FAMILY = 'CydFont' as const;

/**
 * Type definition for all available icon names in the custom font
 *
 * This type ensures type safety when using icon names throughout the application.
 * When adding new icons, update this type to include the new icon names.
 */
export type IconNames =
  | 'circle-star'
  | 'wallet-stacked'
  | 'sunset'
  | 'circle-dollor'
  | 'tap-and-pay'
  | 'online-transaction'
  | 'merchant-outlet'
  | 'mobile-wallets'
  | 'card-pin'
  | 'authentication-method'
  | 'atm-withdrawals'
  | 'select-countries'
  | 'card-color'
  | 'card-tag'
  | 'spend-controls'
  | 'portfolio'
  | 'rewards-icon'
  | 'options'
  | 'seed'
  | 'profile'
  | 'wallet-connect'
  | 'loop-object'
  | 'controls'
  | 'activity'
  | 'address-book'
  | 'bell'
  | 'card-success'
  | 'card-wallet'
  | 'documents'
  | 'connect-link'
  | 'manage-premium'
  | 'telegramBW'
  | 'withdraw1'
  | 'sad-face'
  | 'happy-face'
  | 'edit-2'
  | 'nft-icon'
  | 'zap'
  | 'coins-stacked'
  | 'apple-google-icon'
  | 'balance-scale'
  | 'paypal-icon'
  | 'card-plus'
  | 'arrow-left'
  | 'notification'
  | 'share-filled'
  | 'bar-graph'
  | 'refresh'
  | 'shield'
  | 'disconnect'
  | 'connect'
  | 'delete'
  | 'share'
  | 'link'
  | 'shop'
  | 'success'
  | 'swap-vertical'
  | 'swipe'
  | 'verified'
  | 'lock'
  | 'meter'
  | 'gas'
  | 'qr-code'
  | 'arrow-down-left'
  | 'arrow-up-right'
  | 'lock-1'
  | 'pos-machine'
  | 'trend-up-bold'
  | 'heart'
  | 'ibc'
  | 'information'
  | 'qr-scanner'
  | 'tick'
  | 'bar-graph-filled'
  | 'trend-up'
  | 'bookmark'
  | 'settings'
  | 'google'
  | 'left-hand-pamp'
  | 'withdraw'
  | 'card-load-filled'
  | 'card-load'
  | 'left-hand-pamp-filled'
  | 'close'
  | 'account-plus'
  | 'chevron-left'
  | 'chevron-up'
  | 'globe'
  | 'shield-tick'
  | 'home'
  | 'chevron-down'
  | 'chevron-right'
  | 'telegram'
  | 'wallet-multiple'
  | 'airplane'
  | 'merchant'
  | 'wireless-right'
  | 'atm-cash'
  | 'credit'
  | 'visa'
  | 'card'
  | 'freeze'
  | 'options-vertical'
  | 'web-filled'
  | 'apple'
  | 'debit'
  | 'key'
  | 'copy'
  | 'headphone'
  | 'wallet'
  | 'note'
  | 'wireless-left'
  | 'account-share'
  | 'web'
  | 'swap-horizontal'
  | 'tools-wrench-screwdriver'
  | 'home-filled'
  | 'card-filled'
  | 'star'
  | 'eye'
  | 'eye-closed'
  | 'triangle-down'
  | 'edit'
  | 'debit-card'
  | 'connected'
  | 'contactbook'
  | 'account'
  | 'search'
  | 'activities'
  | 'addphoto'
  | 'bridge';
