export const OCCUPATION_LABEL_TO_CODE_MAP = [
  { label: 'Accountant', value: 'accountant' },
  { label: 'Architect', value: 'architect' },
  { label: 'Artist', value: 'artist' },
  { label: 'Business Owner', value: 'business_owner' },
  { label: 'Consultant', value: 'consultant' },
  { label: 'Doctor', value: 'doctor' },
  { label: 'Engineer', value: 'engineer' },
  { label: 'Entrepreneur', value: 'entrepreneur' },
  { label: 'Financial Analyst', value: 'financial_analyst' },
  { label: 'Lawyer', value: 'lawyer' },
  { label: 'Manager', value: 'manager' },
  { label: 'Marketing Professional', value: 'marketing_professional' },
  { label: 'Nurse', value: 'nurse' },
  { label: 'Professor', value: 'professor' },
  { label: 'Programmer', value: 'programmer' },
  { label: 'Sales Professional', value: 'sales_professional' },
  { label: 'Student', value: 'student' },
  { label: 'Teacher', value: 'teacher' },
  { label: 'Other', value: 'other' },
];
