export type EVM_ONLY_CHAINS_TYPE =
  | 'ETH'
  | 'POLYGON'
  | 'AVALANCHE'
  | 'FANTOM'
  | 'ARBITRUM'
  | 'OPTIMISM'
  | 'BSC'
  | 'SHARDEUM'
  | 'SHARDEUM_SPHINX';

export type EVM_CHAINS_TYPE = EVM_ONLY_CHAINS_TYPE | 'EVMOS';

export type COSMOS_CHAINS_TYPE =
  | 'COSMOS'
  | 'OSMOSIS'
  | 'JUNO'
  | 'STARGAZE'
  | 'EVMOS'
  | 'NOBLE';

export type ALL_CHAINS_TYPE = EVM_CHAINS_TYPE | COSMOS_CHAINS_TYPE;
