import analytics from '@react-native-firebase/analytics';

export const AnalyticEvent = {
  TRANSACTION_RECEIPT_RECEIVED: 'transaction_receipt',
  COSMOS_SIGNAMINO: 'cosmos_provider_signAmino',
  COSMOS_SIGNDIRECT: 'cosmos_provider_signAmino',
  COSMOS_METHOD_NOTFOUND: 'cosmos_provider_methodNotFound_error',
  COSMOS_PROVIDER_ERROR: 'cosmos_provider_error',
  JSON_RPC_ERROR: 'internal_JSON_RPC_error',
  WEB3_METHOD_NOTFOUND: 'web3_method_not_supported',
  SKIP_API_BRIDGE_ERROR: 'bridge_falied',
  SKIP_API_BRIDGE_SUCESS: 'bridge_sucess',
  SKIP_API_BRIDGE_QUOTE: 'bridge_quote',
  DEFAULT_CARD_CONTROLS: 'default_card_controls',
  GET_NEW_CARD: 'get_new_card',
  SOCIAL_LOGIN_EVM: 'social_login_evm',
  SOCIAL_LOGIN_SOLANA: 'social_login_solana',
  SIGN_WALLET_CONNECT_MSG: 'sign_wallet_connect_msg',
  SWAP_QUOTE_ERROR: 'SWAP_QUOTE_ERROR',
  BRIDGE_QUOTE_ERROR: 'BRIDGE_QUOTE_ERROR',
  BRIDGE_SUCCESS: 'BRIDGE_SUCCESS',
  BRIDGE_ERROR: 'BRIDGE_ERROR',
  SWAP_SUCCESS: 'SWAP_SUCCESS',
  SWAP_ERROR: 'SWAP_ERROR',
  GAS_OPTIMISATION: 'gas_optimisation',
  TRANSACTION_SUBMIT: 'transaction_submit',
  TRANSACTION_PERSONAL_SIGN: 'transaction_personal_sign',
  ETH_SIGN_TYPED_DATA_V4: 'eth_signtypeddata_v4',
  UNKNOWN_RPC_CALL: 'unknown_rpc_call',
  CARD_CHANNEL_TOGGLE: 'card_channel_toggle',
  CARD_LIMIT_CHANGE: 'card_limit_change',
  CARD_SETTINGS_RESET: 'card_settings_reset',
  CARD_LOAD: 'card_load',
  EXPLORE_PREMIUM_LOAD_CARD_CTA: 'explore_premium_load_card_cta',
  EXPLORE_PREMIUM_TN_DETAIL_CTA: 'explore_premium_tn_detail_cta',
  EXPLORE_PREMIUM_CARD_PAGE_CTA: 'explore_premium_card_page_cta',
  VISITED_DEFI_OVERVIEW_SCREEN: 'visited_defi_overview_screen',
  INSIDE_COINBASE_PAY: 'inside_coinbase_pay',
  VISITED_NFT_HOLDINGS_SCREEN: 'visited_nft_holdings_screen',
  VISITED_NFT_OVERVIEW_SCREEN: 'visited_nft_overview_screen',
  CONNECT_USING_WALLET_CONNECT: 'connect_using_wallet_connect',
  WALLET_CONNECT_URL_SCAN: 'wallet_connect_url_scan',
  CARD_DECLINE_ADD_TXN_CTA: 'card_decline_add_txn_cta',
  CARD_TXN_CTA: 'card_txn_cta',
  SHORTCUTS_BUTTON_CLICK: 'shortcuts_button_click',
  VISITED_TOKEN_OVERVIEW_PAGE: 'visited_token_overview_page',
  ACTIVITY_SCREEN_VIEW: 'activity_screen_view',
  WEB3_INSTANCE_UNDEFINED_PROPS: 'web3Instance_undefined_props',
  BROWSER_ADDRESSBAR: 'browser_addressbar',
  BROWSER_RECENT_URL_CLICK: 'browser_recent_url_click',
  BROWSER_CLEAR_HISTORY: 'browser_clear_history',
  BROWSER_HISTORY_URL_CLICK: 'browser_history_url_click',
  BROWSER_HISTORY_URL_CLEAR: 'browser_history_url_clear',
  BROWSER_FAVOURITE_URL_CLICK: 'browser_favourite_url_click',
  TRANSACTION_DETAILS_THIS_WAS_ME: 'transaction_details_this_was_me',
  TRANSACTION_DETAILS_THIS_ISNT_ME: 'transaction_details_this_isnt_me',
  TRANSACTION_DETAILS_ADD_COUNTRY: 'transaction_details_add_country',
  TRANSACTION_DETAILS_ACTIVATE_CARD: 'transaction_details_activate_card',
  TRANSACTION_DETAILS_SHARE: 'transaction_details_share',
  TRANSACTION_DETAILS_VIEW_MERCHANT: 'transaction_details_view_merchant',
  TRANSACTION_DETAILS_VIEWED: 'transaction_details_viewed',
  TRANSACTION_DETAILS_EXPLORE_PREMIUM: 'transaction_details_explore_premium',
  TRANSACTION_DETAILS_REPORT_ISSUE: 'transaction_details_report_issue',
  TRANSACTION_DETAILS_CONTACT_SUPPORT: 'transaction_details_contact_support',
  TRANSACTION_APPROVAL_APPROVE: 'transaction_approval_approve',
  TRANSACTION_APPROVAL_APPROVE_SUCCESS: 'transaction_approval_approve_success',
  TRANSACTION_APPROVAL_APPROVE_FAILED: 'transaction_approval_approve_failed',
  REPORT_TRANSACTION_MODAL_OPENED: 'report_transaction_modal_opened',
  REPORT_TRANSACTION_SUBMIT_ATTEMPT: 'report_transaction_submit_attempt',
  REPORT_TRANSACTION_SUBMIT_SUCCESS: 'report_transaction_submit_success',
  REPORT_TRANSACTION_SUBMIT_ERROR: 'report_transaction_submit_error',
  REPORT_TRANSACTION_SUBMIT_EXCEPTION: 'REPORT_TRANSACTION_SUBMIT_EXCEPTION',
  REPORT_TRANSACTION_ISSUE_SELECTED: 'report_transaction_issue_selected',
  REPORT_TRANSACTION_FILE_SELECT_ATTEMPT:
    'report_transaction_file_select_attempt',
  REPORT_TRANSACTION_MAX_FILES_ERROR: 'report_transaction_max_files_error',
  REPORT_TRANSACTION_FILES_SELECTED: 'report_transaction_files_selected',
  REPORT_TRANSACTION_INVALID_FILE_ERROR:
    'report_transaction_invalid_file_error',
  REPORT_TRANSACTION_FILE_SIZE_ERROR: 'report_transaction_file_size_error',
  REPORT_TRANSACTION_FILE_ADDED: 'report_transaction_file_added',
  REPORT_TRANSACTION_FILE_SELECTION_ERROR:
    'report_transaction_file_selection_error',
  REPORT_TRANSACTION_FILE_DELETED: 'report_transaction_file_deleted',
  THREE_D_SECURE_MODAL_VIEWED: 'three_d_secure_modal_viewed',
  THREE_D_SECURE_TIMER_EXPIRED: 'three_d_secure_timer_expired',
  THREE_D_SECURE_APPROVE: 'three_d_secure_approve',
  THREE_D_SECURE_APPROVE_SUCCESS: 'three_d_secure_approve_success',
  THREE_D_SECURE_APPROVE_FAILED: 'three_d_secure_approve_failed',
  THREE_D_SECURE_DECLINE: 'three_d_secure_decline',
  THREE_D_SECURE_DECLINE_SUCCESS: 'three_d_secure_decline_success',
  THREE_D_SECURE_DECLINE_FAILED: 'three_d_secure_decline_failed',
  THREE_D_SECURE_CLOSE_WITH_DECLINE: 'three_d_secure_close_with_decline',
  THREE_D_SECURE_DISMISSED: 'three_d_secure_dismissed',
  TRANSACTION_DECLINE_MODAL_VIEWED: 'transaction_decline_modal_viewed',
  TRANSACTION_DECLINE_APPROVE: 'transaction_decline_approve',
  TRANSACTION_DECLINE_APPROVE_SUCCESS: 'transaction_decline_approve_success',
  TRANSACTION_DECLINE_APPROVE_FAILED: 'transaction_decline_approve_failed',
  TRANSACTION_DECLINE_APPROVE_EXCEPTION:
    'transaction_decline_approve_exception',
  TRANSACTION_DECLINE_REPORT_FRAUD: 'transaction_decline_report_fraud',
  TRANSACTION_DECLINE_REPORT_SUCCESS: 'transaction_decline_report_success',
  TRANSACTION_DECLINE_REPORT_FAILED: 'transaction_decline_report_failed',
  TRANSACTION_DECLINE_REPORT_EXCEPTION: 'transaction_decline_report_exception',
  TRANSACTION_DECLINE_REPORT_CANCELED: 'transaction_decline_report_canceled',
  TRANSACTION_DECLINE_MODAL_DISMISSED: 'transaction_decline_modal_dismissed',
  CARD_CONTROLS_REQUEST_HIGHER_LIMIT_SUBMIT:
    'card_controls_request_higher_limit_submit',
  CARD_CONTROLS_UPDATE_COUNTRIES: 'card_controls_update_countries',
  CARD_CONTROLS_EXPLORE_PREMIUM: 'card_controls_explore_premium',
  CARD_CONTROLS_SELECT_COUNTRY: 'card_controls_select_country',
};

export const logAnalyticsToFirebase = (
  event: string,
  data: Record<string, any> = {},
): void => {
  void analytics()
    .logEvent(event, data)
    .catch(error => {
      console.error('Error logging event to Firebase:', error);
    });
};
