import analytics from '@react-native-firebase/analytics';

export const AnalyticEvent = {
  TRANSACTION_RECEIPT_RECEIVED: 'transaction_receipt',
  COSMOS_SIGNAMINO: 'cosmos_provider_signAmino',
  COSMOS_SIGNDIRECT: 'cosmos_provider_signAmino',
  COSMOS_METHOD_NOTFOUND: 'cosmos_provider_methodNotFound_error',
  COSMOS_PROVIDER_ERROR: 'cosmos_provider_error',
  JSON_RPC_ERROR: 'internal_JSON_RPC_error',
  WEB3_METHOD_NOTFOUND: 'web3_method_not_supported',
  SKIP_API_BRIDGE_ERROR: 'bridge_falied',
  SKIP_API_BRIDGE_SUCESS: 'bridge_sucess',
  SKIP_API_BRIDGE_QUOTE: 'bridge_quote',
  DEFAULT_CARD_CONTROLS: 'default_card_controls',
  GET_NEW_CARD: 'get_new_card',
  SOCIAL_LOGIN_EVM: 'social_login_evm',
  SOCIAL_LOGIN_SOLANA: 'social_login_solana',
  SIGN_WALLET_CONNECT_MSG: 'sign_wallet_connect_msg',
  SWAP_QUOTE_ERROR: 'SWAP_QUOTE_ERROR',
  BRIDGE_QUOTE_ERROR: 'BRIDGE_QUOTE_ERROR',
  BRIDGE_SUCCESS: 'BRIDGE_SUCCESS',
  BRIDGE_ERROR: 'BRIDGE_ERROR',
  SWAP_SUCCESS: 'SWAP_SUCCESS',
  SWAP_ERROR: 'SWAP_ERROR',
  GAS_OPTIMISATION: 'gas_optimisation',
  TRANSACTION_SUBMIT: 'transaction_submit',
  TRANSACTION_PERSONAL_SIGN: 'transaction_personal_sign',
  ETH_SIGN_TYPED_DATA_V4: 'eth_signtypeddata_v4',
  UNKNOWN_RPC_CALL: 'unknown_rpc_call',
  CARD_CHANNEL_TOGGLE: 'card_channel_toggle',
  CARD_LIMIT_CHANGE: 'card_limit_change',
  CARD_SETTINGS_RESET: 'card_settings_reset',
  CARD_LOAD: 'card_load',
  EXPLORE_PREMIUM_LOAD_CARD_CTA: 'explore_premium_load_card_cta',
  EXPLORE_PREMIUM_TN_DETAIL_CTA: 'explore_premium_tn_detail_cta',
  EXPLORE_PREMIUM_CARD_PAGE_CTA: 'explore_premium_card_page_cta',
  VISITED_DEFI_OVERVIEW_SCREEN: 'visited_defi_overview_screen',
  INSIDE_COINBASE_PAY: 'inside_coinbase_pay',
  VISITED_NFT_HOLDINGS_SCREEN: 'visited_nft_holdings_screen',
  VISITED_NFT_OVERVIEW_SCREEN: 'visited_nft_overview_screen',
  CONNECT_USING_WALLET_CONNECT: 'connect_using_wallet_connect',
  WALLET_CONNECT_URL_SCAN: 'wallet_connect_url_scan',
  CARD_DECLINE_ADD_TXN_CTA: 'card_decline_add_txn_cta',
  CARD_TXN_CTA: 'card_txn_cta',
  SHORTCUTS_BUTTON_CLICK: 'shortcuts_button_click',
  VISITED_TOKEN_OVERVIEW_PAGE: 'visited_token_overview_page',
  ACTIVITY_SCREEN_VIEW: 'activity_screen_view',
  WEB3_INSTANCE_UNDEFINED_PROPS: 'web3Instance_undefined_props',
  BROWSER_ADDRESSBAR: 'browser_addressbar',
  BROWSER_RECENT_URL_CLICK: 'browser_recent_url_click',
  BROWSER_CLEAR_HISTORY: 'browser_clear_history',
  BROWSER_HISTORY_URL_CLICK: 'browser_history_url_click',
  BROWSER_HISTORY_URL_CLEAR: 'browser_history_url_clear',
  BROWSER_FAVOURITE_URL_CLICK: 'browser_favourite_url_click',
};

export const logAnalyticsToFirebase = (
  event: string,
  data: Record<string, any> = {},
): void => {
  void analytics().logEvent(event, data);
};
