name: Deploy Android App to PlayStore

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - beta

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0' # or whatever version you're using

      - name: Configure npm
        run: |
          echo "@cypherd-io:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies and clean build
        run: npm ci --legacy-peer-deps
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Gradle Gradle
        id: clean
        run: cd android && ./gradlew clean

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{secrets.SIGNING_KEY}}
          alias: ${{secrets.ALIAS}}
          keyStorePassword: ${{secrets.KEY_STORE_PASSWORD}}
          keyPassword: ${{secrets.KEY_PASSWORD}}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Create service_account.json
        id: createServiceAccont
        run: echo `${{secrets.SERVICE_ACCOUNT_JSON}}` > service_account.json

      - name: Deploy to Play Store internal testing
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.cypherd.androidwallet
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          changesNotSentForReview: false
          whatsNewDirectory: android/whatsnew
